const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
  readDir:  (path)          => ipcRenderer.invoke('read-dir', path),
  readFile: (path)          => ipcRenderer.invoke('read-file', path),
  writeFile:(path, content) => ipcRenderer.invoke('write-file', path, content),
  openFolderDialog: ()              => ipcRenderer.invoke('open-folder-dialog'),
  createProject:  (opts)          => ipcRenderer.invoke('create-project', opts),
  fsNewFile:      (path)          => ipcRenderer.invoke('fs:new-file', path),
  fsNewFolder:    (path)          => ipcRenderer.invoke('fs:new-folder', path),
  fsRename:       (old_, new_)    => ipcRenderer.invoke('fs:rename', old_, new_),
  fsDelete:       (path)          => ipcRenderer.invoke('fs:delete', path),
  terminalStart:      (cwd)        => ipcRenderer.invoke('terminal:start', cwd),
  terminalWrite:      (data)       => ipcRenderer.send('terminal:write', data),
  terminalResize:     (cols, rows) => ipcRenderer.send('terminal:resize', cols, rows),
  terminalKill:       ()           => ipcRenderer.send('terminal:kill'),
  onTerminalData:     (cb)  => ipcRenderer.on('terminal:data', (_e, d) => cb(d)),
  onTerminalExit:     (cb)  => ipcRenderer.on('terminal:exit', (_e, code) => cb(code)),
  gitIsRepo:  (dir)          => ipcRenderer.invoke('git:is-repo', dir),
  gitBranch:  (dir)          => ipcRenderer.invoke('git:branch', dir),
  gitStatus:  (dir)          => ipcRenderer.invoke('git:status', dir),
  gitAdd:     (dir, files)   => ipcRenderer.invoke('git:add', dir, files),
  gitUnstage: (dir, files)   => ipcRenderer.invoke('git:unstage', dir, files),
  gitCommit:  (dir, msg)     => ipcRenderer.invoke('git:commit', dir, msg),
  gitLog:     (dir)          => ipcRenderer.invoke('git:log', dir),
  lspRequest:  (lang, method, params) => ipcRenderer.invoke('lsp:request', lang, method, params),
  lspNotify:   (lang, method, params) => ipcRenderer.send('lsp:notify', lang, method, params),
  lspSetRoot:      (rootPath) => ipcRenderer.invoke('lsp:set-root', rootPath),
  lspListServers:  ()         => ipcRenderer.invoke('lsp:list-servers'),
  onLspNotification: (cb) => ipcRenderer.on('lsp:notification', (_e, data) => cb(data)),
  simGetDevices:     ()             => ipcRenderer.invoke('sim:get-devices'),
  simCheckToolchain: (id)           => ipcRenderer.invoke('sim:check-toolchain', id),
  simCompile:        (opts)         => ipcRenderer.invoke('sim:compile', opts),
  simStart:          (opts)         => ipcRenderer.invoke('sim:start', opts),
  simStop:           ()             => ipcRenderer.send('sim:stop'),
  simWrite:          (data)         => ipcRenderer.send('sim:write', data),
  onSimSerial:       (cb)           => ipcRenderer.on('sim:serial', (_e, d) => cb(d)),
  onSimGpio:         (cb)           => ipcRenderer.on('sim:gpio',   (_e, d) => cb(d)),
  onSimExit:         (cb)           => ipcRenderer.on('sim:exit',   (_e, c) => cb(c)),
  pkgDetect:       (rootPath)      => ipcRenderer.invoke('pkg:detect', rootPath),
  pkgCheckTool:    (tool)          => ipcRenderer.invoke('pkg:check-tool', tool),
  pkgList:         (opts)          => ipcRenderer.invoke('pkg:list', opts),
  pkgInstall:      (opts)          => ipcRenderer.invoke('pkg:install', opts),
  pkgUninstall:    (opts)          => ipcRenderer.invoke('pkg:uninstall', opts),
  pkgSearchVcpkg:  (query)         => ipcRenderer.invoke('pkg:search-vcpkg', query),
  pkgSearchArduino:(query)         => ipcRenderer.invoke('pkg:search-arduino', query),
  onPkgLog:        (cb)            => ipcRenderer.on('pkg:log', (_e, d) => cb(d)),
  minimize: ()              => ipcRenderer.invoke('window-minimize'),
  maximize: ()              => ipcRenderer.invoke('window-maximize'),
  close:    ()              => ipcRenderer.invoke('window-close'),
})
