export const jankTheme = {
  bg:           '#FFFAF5',
  bgEditor:     '#FFF6EE',
  bgSidebar:    '#FFF0E0',
  bgTitlebar:   '#F5E6D3',
  accent:       '#E8793A',
  accentHover:  '#D4651E',
  text:         '#3D2B1F',
  textMuted:    '#A07850',
  border:       '#E8D5C0',
  lineHighlight:'#FDECD8',
  selection:    '#F5C9A0',
}

export const monacoTheme = {
  base: 'vs',
  inherit: false,
  rules: [
    { token: '',                foreground: '3D2B1F', background: 'FFF6EE' },
    { token: 'comment',         foreground: 'A07850', fontStyle: 'italic' },
    { token: 'keyword',         foreground: 'C45A1A', fontStyle: 'bold' },
    { token: 'string',          foreground: '8B6914' },
    { token: 'number',          foreground: 'B05A2A' },
    { token: 'type',            foreground: 'C47A35' },
    { token: 'function',        foreground: '9B4A0A' },
    { token: 'variable',        foreground: '3D2B1F' },
    { token: 'operator',        foreground: 'C45A1A' },
    { token: 'delimiter',       foreground: '8B6040' },
  ],
  colors: {
    'editor.background':                  '#FFF6EE',
    'editor.foreground':                  '#3D2B1F',
    'editor.lineHighlightBackground':     '#FDECD8',
    'editor.selectionBackground':         '#F5C9A0',
    'editor.inactiveSelectionBackground': '#F5DEC0',
    'editorCursor.foreground':            '#E8793A',
    'editorLineNumber.foreground':        '#C8A882',
    'editorLineNumber.activeForeground':  '#E8793A',
    'editorGutter.background':            '#FFF6EE',
    'editorWidget.background':            '#FFF0E0',
    'editorWidget.border':                '#E8D5C0',
    'editorSuggestWidget.background':     '#FFF0E0',
    'editorSuggestWidget.border':         '#E8D5C0',
    'editorSuggestWidget.selectedBackground': '#F5C9A0',
    'scrollbarSlider.background':         '#E8C9A088',
    'scrollbarSlider.hoverBackground':    '#E8793A88',
  },
}
